### ISSUE TITLE
Feature Request : Python implementation

### ISSUE THREAD

**Issue by transferlearnings** [malaria-atlas-project/malariaAtlas#31]
Hi,

Wanted to say thanks for all the time and effort that went into this great package! Are there any plans to have this implemented as a Python package?

Regards,

Reuben

**Comment by timcdlucas** [comment]
Hi,

Thanks for getting in touch. No there is currently no plan for a python implementation. If you or someone you know fancied making one, we'd love to support that!

Otherwise, I'll bear it in mind. As far as I know, none of us that have worked much on this package know python well, and we'd be learning package building from scratch. If we do port it to python I imagine we'd do a stripped back version and skip out lots of the plotting functions. If that sounds like a terrible idea please tell me and I'll also bear it in mind!

I guess the other approach is to consider a simpler library of wrapper functions using rpy2 or something. But I don't know how seamless it is.

**Comment by timcdlucas** [comment]
Great! The first two functions to try would be getPR and listPoints. 

Hopefully the URLs in the source code is enough to get you started. If you need more information on the server stuff I'll put you in touch with the people (Joe) that run our geoserver.

So let us know how you go and absolutely ask if you need any help.

**Comment by timcdlucas** [comment]
As we've discussed this and decided that you (and not us!) are going to do this, I'll close the issue.
Thanks!
